# - platform: mqtt
  # name: "PAPP"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: ' {{ value_json.PAPP | is_defined / 1000 }} '
  # unit_of_measurement: 'KVA'
  # icon: mdi:speedometer
# - platform: mqtt
  # name: "IINST"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: "{{ value_json.IINST | is_defined}}"
  # unit_of_measurement: 'A'
# - platform: mqtt
  # name: "HCHC"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.HCHC | is_defined / 1000}}'
  # unit_of_measurement: 'Kwh'
# - platform: mqtt
  # name: "HCHP"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.HCHP | is_defined / 1000}}'
  # unit_of_measurement: 'Kwh'
# - platform: mqtt
  # name: "ISOUSC"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.ISOUSC | is_defined}}'
  # unit_of_measurement: 'A'
# - platform: mqtt
  # name: "PTEC"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.PTEC | is_defined}}'
# - platform: mqtt
  # name: "IMAX"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.IMAX | is_defined}}'
  # unit_of_measurement: 'A'
# - platform: mqtt
  # name: "HHPHC"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.HHPHC | is_defined}}'
# - platform: mqtt
  # name: "MOTDETAT"
  # state_topic: "sensors/home/energie/compteur/conso"
  # value_template: '{{ value_json.MOTDETAT | is_defined}}'
- platform: template
  sensors:
    edf_daily:
      friendly_name: Daily Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.edf_hp_daily')|float  + states('sensor.edf_hc_daily')|float)| round(0)  }}"
    edf_monthly:
      friendly_name: Monthly Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.edf_hp_monthly')|float  + states('sensor.edf_hc_monthly')|float)| round(0)  }}"
    edf_yearly:
      friendly_name: Monthly Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.edf_hp_yearly')|float  + states('sensor.edf_hc_yearly')|float)| round(0)  }}"
    edf_daily_euros:
      friendly_name: Daily Energy
      unit_of_measurement: €
      value_template: "{{ ((states('sensor.edf_hp_daily')|float  + states('sensor.edf_hc_daily')|float )*0.1554 )| round(2)}}"
    edf_monthly_euros:
      friendly_name: Monthly Energy
      unit_of_measurement: €
      value_template: "{{ ((states('sensor.edf_hp_monthly')|float  + states('sensor.edf_hc_monthly')|float )*0.1554)| round(2) }}"
    edf_yearly_euros:
      friendly_name: Monthly Energy
      unit_of_measurement: €
      value_template: "{{ ((states('sensor.edf_hp_yearly')|float  + states('sensor.edf_hc_yearly')|float )*0.1554)| round(2) }}"
      
 ############################ END TELEINFO CONSOMTION #######################################"     
      
 ############################ START MUSIQUE ################################################
 
- platform: rest
  name: volume arylic
  resource: http://192.168.1.50/httpapi.asp?command=setPlayerCmd:Vol--n
  unit_of_measurement: '%'
- platform: rest
  name: status arylic
  resource: http://192.168.1.50/httpapi.asp?command=getPlayerStatus
  value_template: '{{ value_json.status }}'



##########################Raspberry monitor

# System monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: last_boot